spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://10.2.13.20:3306/testobject?characterEncoding-utf-8&useSSL=false
eureka:
  client:
    service-url: http://10.2.13.32:8761/eureka/
